# Generated by Django 4.1.1 on 2022-09-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='listened_to',
            field=models.BooleanField(null=True),
        ),
    ]
