# Generated by Django 4.1.1 on 2022-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_api', '0004_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='added_by',
            field=models.CharField(default=True, max_length=32),
        ),
    ]
